// Master Production Default Database
// Automatically populated from complete ERP snapshot

export const MASTER_INITIAL_PRODUCTS = [
  {
    "id": "PRD-ICEGOLD-01",
    "sku": "ICE60KHAM",
    "barcode": "880192837499",
    "name": "Icegold A4 Size Kham",
    "category": "Print Items",
    "brand": "Icegold",
    "unit": "pcs",
    "stock": 500,
    "minStock": 50,
    "purchasePriceCNY": 0,
    "currentLandedCost": 45,
    "retailPrice": 85,
    "wholesalePrice": 75,
    "projectPrice": 70,
    "dealerPrice": 65,
    "isSerialTracked": false
  },
  {
    "id": "PRD-03594",
    "sku": "BOOKPMT",
    "barcode": "880273706970",
    "name": "A Tale of A  Dark Period  Book",
    "category": "Print Items",
    "brand": "No",
    "unit": "pcs",
    "stock": 500,
    "minStock": 10,
    "purchasePriceCNY": 500,
    "currentLandedCost": 450,
    "retailPrice": 800,
    "wholesalePrice": 800,
    "projectPrice": 800,
    "dealerPrice": 800,
    "isSerialTracked": true
  },
  {
    "id": "PRD-29441",
    "sku": "COATPINTRANSP",
    "barcode": "880210121182",
    "name": "Coat Pin",
    "category": "Gift Items",
    "brand": "no",
    "unit": "pcs",
    "stock": 200,
    "minStock": 10,
    "purchasePriceCNY": 500,
    "currentLandedCost": 40,
    "retailPrice": 150,
    "wholesalePrice": 150,
    "projectPrice": 150,
    "dealerPrice": 150,
    "isSerialTracked": true
  },
  {
    "id": "PRD-23851",
    "sku": "FIBERINSTALLATIONLYING",
    "barcode": "880657795464",
    "name": "Fiber Cable Installation (Laying & Pulling Run & Dressing Tagging)",
    "category": "Networking",
    "brand": "No",
    "unit": "meter",
    "stock": 20000,
    "minStock": 10,
    "purchasePriceCNY": 500,
    "currentLandedCost": 10,
    "retailPrice": 25,
    "wholesalePrice": 25,
    "projectPrice": 25,
    "dealerPrice": 25,
    "isSerialTracked": true
  },
  {
    "id": "PRD-52661",
    "sku": "LANINSTALLATION",
    "barcode": "880252807128",
    "name": "Copper Cable Installation, Faceplate & Modular Punch, Node Dressing, Tagging with PVC Pipe Wiring",
    "category": "Networking",
    "brand": "NO",
    "unit": "unit",
    "stock": 2000,
    "minStock": 10,
    "purchasePriceCNY": 500,
    "currentLandedCost": 400,
    "retailPrice": 1050,
    "wholesalePrice": 1050,
    "projectPrice": 1050,
    "dealerPrice": 1050,
    "isSerialTracked": true
  },
  {
    "id": "PRD-93390",
    "sku": "32URACKINSTALLATION",
    "barcode": "880638339631",
    "name": "32U Floor Mount Network Rack with Mesh Door (Fron",
    "category": "Networking",
    "brand": "No",
    "unit": "unit",
    "stock": 20,
    "minStock": 10,
    "purchasePriceCNY": 500,
    "currentLandedCost": 300,
    "retailPrice": 800,
    "wholesalePrice": 800,
    "projectPrice": 800,
    "dealerPrice": 800,
    "isSerialTracked": true
  },
  {
    "id": "PRD-37605",
    "sku": "18URACKINSTALLATION",
    "barcode": "880932739800",
    "name": "18U Wall Mount Network Rack with Mesh Door (Front) Installation",
    "category": "Networking",
    "brand": "No",
    "unit": "unit",
    "stock": 100,
    "minStock": 10,
    "purchasePriceCNY": 500,
    "currentLandedCost": 200,
    "retailPrice": 500,
    "wholesalePrice": 500,
    "projectPrice": 500,
    "dealerPrice": 500,
    "isSerialTracked": true
  },
  {
    "id": "PRD-77622",
    "sku": "CIVILGROUPCUTTING",
    "barcode": "880737483688",
    "name": "Civil Work With PVC Pipe Laying (Conduit Cutting, Refilling)",
    "category": "Networking",
    "brand": "NO",
    "unit": "meter",
    "stock": 20000,
    "minStock": 10,
    "purchasePriceCNY": 500,
    "currentLandedCost": 40,
    "retailPrice": 100,
    "wholesalePrice": 100,
    "projectPrice": 100,
    "dealerPrice": 100,
    "isSerialTracked": true
  },
  {
    "id": "PRD-45961",
    "sku": "MICRONETRJ45",
    "barcode": "880603450074",
    "name": "Micronet Cat 6 RJ45 Cable Connector",
    "category": "Accessories & Cables",
    "brand": "Micront Connector",
    "unit": "pcs",
    "stock": 500,
    "minStock": 10,
    "purchasePriceCNY": 500,
    "currentLandedCost": 20,
    "retailPrice": 27,
    "wholesalePrice": 27,
    "projectPrice": 27,
    "dealerPrice": 27,
    "isSerialTracked": true
  },
  {
    "id": "PRD-33375",
    "sku": "DAHUA922I",
    "barcode": "880317790705",
    "name": "Dahua PFM922I-6UN-C Cat6 UTP Cable",
    "category": "CCTV & Surveillance",
    "brand": "Dahua",
    "unit": "meter",
    "stock": 15270,
    "minStock": 10,
    "purchasePriceCNY": 500,
    "currentLandedCost": 27,
    "retailPrice": 60,
    "wholesalePrice": 50,
    "projectPrice": 50,
    "dealerPrice": 50,
    "isSerialTracked": true
  },
  {
    "id": "PRD-38649",
    "sku": "DISMOUNT",
    "barcode": "880232319354",
    "name": "CCTV Dismantle and Re-installation",
    "category": "CCTV & Surveillance",
    "brand": "NO",
    "unit": "unit",
    "stock": 1000,
    "minStock": 10,
    "purchasePriceCNY": 500,
    "currentLandedCost": 5000,
    "retailPrice": 1250,
    "wholesalePrice": 1150,
    "projectPrice": 1250,
    "dealerPrice": 1450,
    "isSerialTracked": true
  },
  {
    "id": "PRD-09983",
    "sku": "TX400",
    "barcode": "880379901109",
    "name": "BIXOLON SLP-TX400 4-inch",
    "category": "Print Items",
    "brand": "BIXOLON",
    "unit": "pcs",
    "stock": 22,
    "minStock": 10,
    "purchasePriceCNY": 500,
    "currentLandedCost": 25000,
    "retailPrice": 32500,
    "wholesalePrice": 27000,
    "projectPrice": 28000,
    "dealerPrice": 28000,
    "isSerialTracked": true
  },
  {
    "id": "PRD-75069",
    "sku": "CARFLAGVIP",
    "barcode": "880784856846",
    "name": "Car Flag VIP",
    "category": "Accessories",
    "brand": "No",
    "unit": "pcs",
    "stock": 220,
    "minStock": 10,
    "purchasePriceCNY": 500,
    "currentLandedCost": 600,
    "retailPrice": 15000,
    "wholesalePrice": 13500,
    "projectPrice": 12500,
    "dealerPrice": 12000,
    "isSerialTracked": true
  },
  {
    "id": "PRD-90365",
    "sku": "GIFTLEATHER",
    "barcode": "880271492087",
    "name": "Leather Gift Box for Speaker",
    "category": "Gift Items",
    "brand": "no",
    "unit": "pcs",
    "stock": 120,
    "minStock": 10,
    "purchasePriceCNY": 500,
    "currentLandedCost": 1000,
    "retailPrice": 15000,
    "wholesalePrice": 13500,
    "projectPrice": 12500,
    "dealerPrice": 12000,
    "isSerialTracked": true
  },
  {
    "id": "PRD-91532",
    "sku": "COATPINFLAG",
    "barcode": "880198244261",
    "name": "Coat Pin",
    "category": "Accessories",
    "brand": "none",
    "unit": "pcs",
    "stock": 200,
    "minStock": 10,
    "purchasePriceCNY": 500,
    "currentLandedCost": 120,
    "retailPrice": 200,
    "wholesalePrice": 150,
    "projectPrice": 180,
    "dealerPrice": 150,
    "isSerialTracked": true
  },
  {
    "id": "PRD-67339",
    "sku": "PACGOODS",
    "barcode": "880880980741",
    "name": "Outdoor PAC Shifting Equepments",
    "category": "CCTV & Surveillance",
    "brand": "None",
    "unit": "set",
    "stock": 20,
    "minStock": 10,
    "purchasePriceCNY": 500,
    "currentLandedCost": 10000,
    "retailPrice": 15000,
    "wholesalePrice": 13500,
    "projectPrice": 12500,
    "dealerPrice": 12000,
    "isSerialTracked": true
  },
  {
    "id": "PRD-001",
    "sku": "SKU-CCTV-4MP-DOME",
    "barcode": "880192837401",
    "name": "CCTV Camera (4MP Outdoor IR Dome IP Camera)",
    "category": "CCTV & Surveillance",
    "brand": "Hikvision",
    "unit": "pcs",
    "stock": 40,
    "minStock": 25,
    "purchasePriceCNY": 500,
    "currentLandedCost": 10000,
    "retailPrice": 15000,
    "wholesalePrice": 13500,
    "projectPrice": 12500,
    "dealerPrice": 12000,
    "isSerialTracked": true
  },
  {
    "id": "PRD-002",
    "sku": "SKU-NET-SW24G",
    "barcode": "880192837402",
    "name": "TP-Link 24-Port Gigabit Managed PoE+ Switch",
    "category": "Networking",
    "brand": "TP-Link",
    "unit": "pcs",
    "stock": 8,
    "minStock": 12,
    "purchasePriceCNY": 1250,
    "currentLandedCost": 24000,
    "retailPrice": 34000,
    "wholesalePrice": 31000,
    "projectPrice": 29500,
    "dealerPrice": 28500,
    "isSerialTracked": true
  },
  {
    "id": "PRD-003",
    "sku": "SKU-CCTV-NVR16",
    "barcode": "880192837403",
    "name": "Hikvision 16-Channel 4K NVR with 2-SATA",
    "category": "CCTV & Surveillance",
    "brand": "Hikvision",
    "unit": "unit",
    "stock": 5,
    "minStock": 8,
    "purchasePriceCNY": 850,
    "currentLandedCost": 16500,
    "retailPrice": 24500,
    "wholesalePrice": 22000,
    "projectPrice": 20500,
    "dealerPrice": 19800,
    "isSerialTracked": true
  },
  {
    "id": "PRD-004",
    "sku": "SKU-NET-CABLE-CAT6",
    "barcode": "880192837404",
    "name": "Cat6 UTP Pure Copper Industrial Cable (305m)",
    "category": "Networking",
    "brand": "D-Link",
    "unit": "box",
    "stock": 65,
    "minStock": 20,
    "purchasePriceCNY": 480,
    "currentLandedCost": 9200,
    "retailPrice": 13500,
    "wholesalePrice": 12200,
    "projectPrice": 11500,
    "dealerPrice": 11000,
    "isSerialTracked": false
  },
  {
    "id": "PRD-005",
    "sku": "SKU-SEC-WALKIE-DMR",
    "barcode": "880192837405",
    "name": "Motorola Digital DMR Walkie Talkie 5W",
    "category": "Security & Wireless",
    "brand": "Motorola",
    "unit": "set",
    "stock": 32,
    "minStock": 15,
    "purchasePriceCNY": 380,
    "currentLandedCost": 7500,
    "retailPrice": 12000,
    "wholesalePrice": 10500,
    "projectPrice": 9800,
    "dealerPrice": 9200,
    "isSerialTracked": true
  },
  {
    "id": "PRD-006",
    "sku": "SKU-PWR-UPS3KVA",
    "barcode": "880192837406",
    "name": "APC Smart-UPS On-Line 3KVA 230V",
    "category": "Data Center & Power",
    "brand": "APC by Schneider",
    "unit": "unit",
    "stock": 14,
    "minStock": 5,
    "purchasePriceCNY": 2800,
    "currentLandedCost": 52000,
    "retailPrice": 75000,
    "wholesalePrice": 68000,
    "projectPrice": 65000,
    "dealerPrice": 62000,
    "isSerialTracked": true
  },
  {
    "id": "PRD-007",
    "sku": "SKU-NET-CISCO-2960X",
    "barcode": "880192837407",
    "name": "Cisco Catalyst 2960-X 48 GigE 4x1G SFP",
    "category": "Networking",
    "brand": "Cisco",
    "unit": "unit",
    "stock": 6,
    "minStock": 4,
    "purchasePriceCNY": 4500,
    "currentLandedCost": 85000,
    "retailPrice": 120000,
    "wholesalePrice": 110000,
    "projectPrice": 105000,
    "dealerPrice": 98000,
    "isSerialTracked": true
  },
  {
    "id": "PRD-008",
    "sku": "SKU-STR-SEAGATE-4TB",
    "barcode": "880192837408",
    "name": "Seagate SkyHawk 4TB Surveillance Hard Drive",
    "category": "CCTV & Surveillance",
    "brand": "Seagate",
    "unit": "pcs",
    "stock": 14,
    "minStock": 10,
    "purchasePriceCNY": 420,
    "currentLandedCost": 8000,
    "retailPrice": 12500,
    "wholesalePrice": 11200,
    "projectPrice": 10500,
    "dealerPrice": 10000,
    "isSerialTracked": true
  }
];

export const MASTER_INITIAL_WAREHOUSE_STOCK = [
  {
    "id": "st-icegold-01",
    "warehouseName": "Project Store (Site Depot)",
    "productName": "Icegold A4 Size Kham",
    "sku": "ICE60KHAM",
    "available": 500,
    "reserved": 0,
    "damaged": 0,
    "unitLandedCost": 45
  },
  {
    "id": "st-03604",
    "warehouseName": "Project Store (Site Depot)",
    "productName": "A Tale of A  Dark Period  Book",
    "sku": "BOOKPMT",
    "available": 500,
    "reserved": 0,
    "damaged": 0,
    "unitLandedCost": 450
  },
  {
    "id": "st-29451",
    "warehouseName": "Project Store (Site Depot)",
    "productName": "Coat Pin",
    "sku": "COATPINTRANSP",
    "available": 200,
    "reserved": 0,
    "damaged": 0,
    "unitLandedCost": 40
  },
  {
    "id": "st-23851",
    "warehouseName": "Project Store (Site Depot)",
    "productName": "Fiber Cable Installation (Laying & Pulling Run & Dressing Tagging)",
    "sku": "FIBERINSTALLATIONLYING",
    "available": 20000,
    "reserved": 0,
    "damaged": 0,
    "unitLandedCost": 10
  },
  {
    "id": "st-52661",
    "warehouseName": "Project Store (Site Depot)",
    "productName": "Copper Cable Installation, Faceplate & Modular Punch, Node Dressing, Tagging with PVC Pipe Wiring",
    "sku": "LANINSTALLATION",
    "available": 2000,
    "reserved": 0,
    "damaged": 0,
    "unitLandedCost": 400
  },
  {
    "id": "st-93390",
    "warehouseName": "Main Warehouse (Tejgaon)",
    "productName": "32U Floor Mount Network Rack with Mesh Door (Fron",
    "sku": "32URACKINSTALLATION",
    "available": 20,
    "reserved": 0,
    "damaged": 0,
    "unitLandedCost": 300
  },
  {
    "id": "st-37605",
    "warehouseName": "Project Store (Site Depot)",
    "productName": "18U Wall Mount Network Rack with Mesh Door (Front) Installation",
    "sku": "18URACKINSTALLATION",
    "available": 100,
    "reserved": 0,
    "damaged": 0,
    "unitLandedCost": 200
  },
  {
    "id": "st-77622",
    "warehouseName": "Project Store (Site Depot)",
    "productName": "Civil Work With PVC Pipe Laying (Conduit Cutting, Refilling)",
    "sku": "CIVILGROUPCUTTING",
    "available": 20000,
    "reserved": 0,
    "damaged": 0,
    "unitLandedCost": 40
  },
  {
    "id": "st-45961",
    "warehouseName": "Project Store (Site Depot)",
    "productName": "Micronet Cat 6 RJ45 Cable Connector",
    "sku": "MICRONETRJ45",
    "available": 500,
    "reserved": 0,
    "damaged": 0,
    "unitLandedCost": 20
  },
  {
    "id": "st-33375",
    "warehouseName": "Project Store (Site Depot)",
    "productName": "Dahua PFM922I-6UN-C Cat6 UTP Cable",
    "sku": "DAHUA922I",
    "available": 15270,
    "reserved": 0,
    "damaged": 0,
    "unitLandedCost": 27
  },
  {
    "id": "st-38649",
    "warehouseName": "Project Store (Site Depot)",
    "productName": "CCTV Dismantle and Re-installation",
    "sku": "DISMOUNT",
    "available": 1000,
    "reserved": 0,
    "damaged": 0,
    "unitLandedCost": 5000
  },
  {
    "id": "st-09983",
    "warehouseName": "Project Store (Site Depot)",
    "productName": "BIXOLON SLP-TX400 4-inch",
    "sku": "TX400",
    "available": 22,
    "reserved": 0,
    "damaged": 0,
    "unitLandedCost": 25000
  },
  {
    "id": "st-75069",
    "warehouseName": "Project Store (Site Depot)",
    "productName": "Car Flag VIP",
    "sku": "CARFLAGVIP",
    "available": 220,
    "reserved": 0,
    "damaged": 0,
    "unitLandedCost": 600
  },
  {
    "id": "st-90366",
    "warehouseName": "Project Store (Site Depot)",
    "productName": "Leather Gift Box for Speaker",
    "sku": "GIFTLEATHER",
    "available": 120,
    "reserved": 0,
    "damaged": 0,
    "unitLandedCost": 1000
  },
  {
    "id": "st-91532",
    "warehouseName": "Project Store (Site Depot)",
    "productName": "Coat Pin",
    "sku": "COATPINFLAG",
    "available": 200,
    "reserved": 0,
    "damaged": 0,
    "unitLandedCost": 120
  },
  {
    "id": "st-67339",
    "warehouseName": "Project Store (Site Depot)",
    "productName": "Outdoor PAC Shifting Equepments",
    "sku": "PACGOODS",
    "available": 20,
    "reserved": 0,
    "damaged": 0,
    "unitLandedCost": 10000
  },
  {
    "id": "st-01",
    "warehouseName": "Main Warehouse (Tejgaon)",
    "productName": "CCTV Camera (4MP Outdoor IR Dome IP Camera)",
    "sku": "SKU-CCTV-4MP-DOME",
    "available": 40,
    "reserved": 0,
    "damaged": 0,
    "unitLandedCost": 10000
  },
  {
    "id": "st-02",
    "warehouseName": "Main Warehouse (Tejgaon)",
    "productName": "TP-Link 24-Port Gigabit Managed PoE+ Switch",
    "sku": "SKU-NET-SW24G",
    "available": 8,
    "reserved": 2,
    "damaged": 0,
    "unitLandedCost": 24000
  },
  {
    "id": "st-03",
    "warehouseName": "Project Store (Site Depot)",
    "productName": "CCTV Camera (4MP Outdoor IR Dome IP Camera)",
    "sku": "SKU-CCTV-4MP-DOME",
    "available": 10,
    "reserved": 0,
    "damaged": 0,
    "unitLandedCost": 10000
  },
  {
    "id": "st-04",
    "warehouseName": "Main Warehouse (Tejgaon)",
    "productName": "Cat6 UTP Pure Copper Industrial Cable (305m)",
    "sku": "SKU-NET-CABLE-CAT6",
    "available": 65,
    "reserved": 0,
    "damaged": 0,
    "unitLandedCost": 9200
  }
];

export const MASTER_INITIAL_STOCK_LEDGER = [
  {
    "id": "led-icegold-01",
    "timestamp": "2026-10-03 14:00",
    "productName": "Icegold A4 Size Kham",
    "warehouseName": "Project Store (Site Depot)",
    "movementType": "OPENING_STOCK",
    "quantityDelta": 500,
    "balanceAfter": 500,
    "unitLandedCost": 45,
    "referenceId": "INIT-ICEGOLD",
    "reasonNotes": "Opening stock for Icegold A4 Size Kham"
  },
  {
    "id": "led-1791015803618",
    "timestamp": "2026-10-03 08:23",
    "productName": "A Tale of A  Dark Period  Book",
    "warehouseName": "Project Store (Site Depot)",
    "movementType": "OPENING_STOCK",
    "quantityDelta": 500,
    "balanceAfter": 500,
    "unitLandedCost": 450,
    "referenceId": "INIT-3618",
    "reasonNotes": "Initial opening inventory balance for A Tale of A  Dark Period  Book"
  },
  {
    "id": "led-1791015429465",
    "timestamp": "2026-10-03 08:17",
    "productName": "Coat Pin",
    "warehouseName": "Project Store (Site Depot)",
    "movementType": "OPENING_STOCK",
    "quantityDelta": 200,
    "balanceAfter": 200,
    "unitLandedCost": 40,
    "referenceId": "INIT-9465",
    "reasonNotes": "Initial opening inventory balance for Coat Pin"
  },
  {
    "id": "led-1790826923852",
    "timestamp": "2026-10-01 03:55",
    "productName": "Fiber Cable Installation (Laying & Pulling Run & Dressing Tagging)",
    "warehouseName": "Project Store (Site Depot)",
    "movementType": "OPENING_STOCK",
    "quantityDelta": 20000,
    "balanceAfter": 20000,
    "unitLandedCost": 10,
    "referenceId": "INIT-3852",
    "reasonNotes": "Initial opening inventory balance for Fiber Cable Installation (Laying & Pulling Run & Dressing Tagging)"
  },
  {
    "id": "led-1790826852661",
    "timestamp": "2026-10-01 03:54",
    "productName": "Copper Cable Installation, Faceplate & Modular Punch, Node Dressing, Tagging with PVC Pipe Wiring",
    "warehouseName": "Project Store (Site Depot)",
    "movementType": "OPENING_STOCK",
    "quantityDelta": 2000,
    "balanceAfter": 2000,
    "unitLandedCost": 400,
    "referenceId": "INIT-2661",
    "reasonNotes": "Initial opening inventory balance for Copper Cable Installation, Faceplate & Modular Punch, Node Dressing, Tagging with PVC Pipe Wiring"
  },
  {
    "id": "led-1790826793391",
    "timestamp": "2026-10-01 03:53",
    "productName": "32U Floor Mount Network Rack with Mesh Door (Fron",
    "warehouseName": "Main Warehouse (Tejgaon)",
    "movementType": "OPENING_STOCK",
    "quantityDelta": 20,
    "balanceAfter": 20,
    "unitLandedCost": 300,
    "referenceId": "INIT-3391",
    "reasonNotes": "Initial opening inventory balance for 32U Floor Mount Network Rack with Mesh Door (Fron"
  },
  {
    "id": "led-1790826737605",
    "timestamp": "2026-10-01 03:52",
    "productName": "18U Wall Mount Network Rack with Mesh Door (Front) Installation",
    "warehouseName": "Project Store (Site Depot)",
    "movementType": "OPENING_STOCK",
    "quantityDelta": 100,
    "balanceAfter": 100,
    "unitLandedCost": 200,
    "referenceId": "INIT-7605",
    "reasonNotes": "Initial opening inventory balance for 18U Wall Mount Network Rack with Mesh Door (Front) Installation"
  },
  {
    "id": "led-1790826677622",
    "timestamp": "2026-10-01 03:51",
    "productName": "Civil Work With PVC Pipe Laying (Conduit Cutting, Refilling)",
    "warehouseName": "Project Store (Site Depot)",
    "movementType": "OPENING_STOCK",
    "quantityDelta": 20000,
    "balanceAfter": 20000,
    "unitLandedCost": 40,
    "referenceId": "INIT-7622",
    "reasonNotes": "Initial opening inventory balance for Civil Work With PVC Pipe Laying (Conduit Cutting, Refilling)"
  },
  {
    "id": "led-1790795172364",
    "timestamp": "2026-09-30 19:06",
    "productName": "Dahua PFM922I-6UN-C Cat6 UTP Cable",
    "warehouseName": "Project Store (Site Depot)",
    "movementType": "PURCHASE_GRN",
    "quantityDelta": 15250,
    "balanceAfter": 15270,
    "unitLandedCost": 27,
    "referenceId": "GRN-2026-2235",
    "reasonNotes": "Goods Received Note processed into Project Store (Site Depot)"
  },
  {
    "id": "led-1790793745962",
    "timestamp": "2026-09-30 18:42",
    "productName": "Micronet Cat 6 RJ45 Cable Connector",
    "warehouseName": "Project Store (Site Depot)",
    "movementType": "OPENING_STOCK",
    "quantityDelta": 500,
    "balanceAfter": 500,
    "unitLandedCost": 20,
    "referenceId": "INIT-5962",
    "reasonNotes": "Initial opening inventory balance for Micronet Cat 6 RJ45 Cable Connector"
  },
  {
    "id": "led-1790793433376",
    "timestamp": "2026-09-30 18:37",
    "productName": "Dahua PFM922I-6UN-C Cat6 UTP Cable",
    "warehouseName": "Project Store (Site Depot)",
    "movementType": "OPENING_STOCK",
    "quantityDelta": 20,
    "balanceAfter": 20,
    "unitLandedCost": 27,
    "referenceId": "INIT-3376",
    "reasonNotes": "Initial opening inventory balance for Dahua PFM922I-6UN-C Cat6 UTP Cable"
  },
  {
    "id": "led-1790790738650",
    "timestamp": "2026-09-30 17:52",
    "productName": "CCTV Dismantle and Re-installation",
    "warehouseName": "Project Store (Site Depot)",
    "movementType": "OPENING_STOCK",
    "quantityDelta": 1000,
    "balanceAfter": 1000,
    "unitLandedCost": 5000,
    "referenceId": "INIT-8650",
    "reasonNotes": "Initial opening inventory balance for CCTV Dismantle and Re-installation"
  },
  {
    "id": "led-1790707609983",
    "timestamp": "2026-09-29 18:46",
    "productName": "BIXOLON SLP-TX400 4-inch",
    "warehouseName": "Project Store (Site Depot)",
    "movementType": "OPENING_STOCK",
    "quantityDelta": 22,
    "balanceAfter": 22,
    "unitLandedCost": 25000,
    "referenceId": "INIT-9983",
    "reasonNotes": "Initial opening inventory balance for BIXOLON SLP-TX400 4-inch"
  },
  {
    "id": "led-1790617304837",
    "timestamp": "2026-09-28 17:41",
    "productName": "Car Flag VIP",
    "warehouseName": "Project Store (Site Depot)",
    "movementType": "PURCHASE_GRN",
    "quantityDelta": 100,
    "balanceAfter": 220,
    "unitLandedCost": 600,
    "referenceId": "GRN-2026-4957",
    "reasonNotes": "Goods Received Note processed into Project Store (Site Depot)"
  },
  {
    "id": "led-1790617291708",
    "timestamp": "2026-09-28 17:41",
    "productName": "Car Flag VIP",
    "warehouseName": "Project Store (Site Depot)",
    "movementType": "PURCHASE_GRN",
    "quantityDelta": 100,
    "balanceAfter": 120,
    "unitLandedCost": 10000,
    "referenceId": "GRN-2026-7536",
    "reasonNotes": "Goods Received Note processed into Project Store (Site Depot)"
  },
  {
    "id": "led-1790617175070",
    "timestamp": "2026-09-28 17:39",
    "productName": "Car Flag VIP",
    "warehouseName": "Project Store (Site Depot)",
    "movementType": "OPENING_STOCK",
    "quantityDelta": 20,
    "balanceAfter": 20,
    "unitLandedCost": 10000,
    "referenceId": "INIT-5070",
    "reasonNotes": "Initial opening inventory balance for Car Flag VIP"
  },
  {
    "id": "led-1790616785634",
    "timestamp": "2026-09-28 17:33",
    "productName": "Leather Gift Box for Speaker",
    "warehouseName": "Project Store (Site Depot)",
    "movementType": "PURCHASE_GRN",
    "quantityDelta": 100,
    "balanceAfter": 120,
    "unitLandedCost": 1000,
    "referenceId": "GRN-2026-8267",
    "reasonNotes": "Goods Received Note processed into Project Store (Site Depot)"
  },
  {
    "id": "led-1790616690366",
    "timestamp": "2026-09-28 17:31",
    "productName": "Leather Gift Box for Speaker",
    "warehouseName": "Project Store (Site Depot)",
    "movementType": "OPENING_STOCK",
    "quantityDelta": 20,
    "balanceAfter": 20,
    "unitLandedCost": 10000,
    "referenceId": "INIT-0366",
    "reasonNotes": "Initial opening inventory balance for Leather Gift Box for Speaker"
  },
  {
    "id": "led-1790614391532",
    "timestamp": "2026-09-28 16:53",
    "productName": "Coat Pin",
    "warehouseName": "Project Store (Site Depot)",
    "movementType": "OPENING_STOCK",
    "quantityDelta": 200,
    "balanceAfter": 200,
    "unitLandedCost": 120,
    "referenceId": "INIT-1532",
    "reasonNotes": "Initial opening inventory balance for Coat Pin"
  },
  {
    "id": "led-1790607167340",
    "timestamp": "2026-09-28 14:52",
    "productName": "Outdoor PAC Shifting Equepments",
    "warehouseName": "Project Store (Site Depot)",
    "movementType": "OPENING_STOCK",
    "quantityDelta": 20,
    "balanceAfter": 20,
    "unitLandedCost": 10000,
    "referenceId": "INIT-7340",
    "reasonNotes": "Initial opening inventory balance for Outdoor PAC Shifting Equepments"
  },
  {
    "id": "led-05",
    "timestamp": "2026-09-24 16:30",
    "productName": "CCTV Camera (4MP Outdoor IR Dome IP Camera)",
    "warehouseName": "Main Warehouse (Tejgaon)",
    "movementType": "PROJECT_ISSUE",
    "quantityDelta": -10,
    "balanceAfter": 40,
    "unitLandedCost": 10000,
    "referenceId": "PRJ-2026-001",
    "reasonNotes": "Consumed 10 pcs for ABC Bank CCTV Installation Project"
  },
  {
    "id": "led-04",
    "timestamp": "2026-09-22 14:15",
    "productName": "CCTV Camera (4MP Outdoor IR Dome IP Camera)",
    "warehouseName": "Main Warehouse (Tejgaon)",
    "movementType": "SALE_INVOICE",
    "quantityDelta": -20,
    "balanceAfter": 50,
    "unitLandedCost": 10000,
    "referenceId": "INV-2026-9002",
    "reasonNotes": "Wholesale sale to Beximco Industrial Fabrics"
  },
  {
    "id": "led-03",
    "timestamp": "2026-09-20 11:00",
    "productName": "CCTV Camera (4MP Outdoor IR Dome IP Camera)",
    "warehouseName": "Main Warehouse (Tejgaon)",
    "movementType": "SALE_INVOICE",
    "quantityDelta": -30,
    "balanceAfter": 70,
    "unitLandedCost": 10000,
    "referenceId": "INV-2026-9001",
    "reasonNotes": "Retail sale to ABC Bank PLC"
  },
  {
    "id": "led-02",
    "timestamp": "2026-09-15 09:30",
    "productName": "CCTV Camera (4MP Outdoor IR Dome IP Camera)",
    "warehouseName": "Main Warehouse (Tejgaon)",
    "movementType": "PURCHASE_GRN",
    "quantityDelta": 100,
    "balanceAfter": 100,
    "unitLandedCost": 10000,
    "referenceId": "GRN-2026-001",
    "reasonNotes": "Received 100 pcs from China Import IMP-2026-001"
  },
  {
    "id": "led-01",
    "timestamp": "2026-09-01 08:00",
    "productName": "CCTV Camera (4MP Outdoor IR Dome IP Camera)",
    "warehouseName": "Main Warehouse (Tejgaon)",
    "movementType": "OPENING_STOCK",
    "quantityDelta": 40,
    "balanceAfter": 40,
    "unitLandedCost": 10000,
    "referenceId": "INIT-2026",
    "reasonNotes": "Opening initial audited balance"
  }
];

export const MASTER_INITIAL_CATEGORIES = [
  "CCTV & Surveillance",
  "Networking",
  "Data Center & Power",
  "Security & Wireless",
  "Accessories & Cables",
  "Fire Safety & Access Control",
  "Stationery & Paper",
  "Office Supplies & Consumables",
  "Accessories",
  "Gift Items",
  "Print Items"
];
